### ISSUE TITLE
Won't install on portable/standalone Comfy - EZ Fix

### ISSUE THREAD

**Issue by Kinglord** [christian-byrne/img2colors-comfyui-node#1]
Hello,

Sadly this won't install on the standalone version of Comfy due to a hardset scikit-image version in 0.2.4 of colornamer which you have hardset in the requirements.

I did a quick test and the node seems to work just fine if i install 0.2.3 which has no hardset scikit-image version.

Just thought I would let you know that it might save a lot of headaches to hardset it down to 0.2.3 unless it really needs 0.2.4 for a reason I'm not aware of. Cheers!

**Comment by christian-byrne** [comment]
Thanks for pointing that out! You're right, scikit-image is pinned in version 0.24.0 of colornamer ([commit](https://github.com/stitchfix/colornamer/commit/8a594152f2b380d086fc149427e058af0a80f1c4)), but it's unpinned in version 0.23.0. I appreciate you testing version 0.23.0 for me. The requirements are updated now.
